# Generated by Django 5.2.1 on 2025-08-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_supportticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.prestigesettings'),
        ),
    ]
