# Generated by Django 5.2.1 on 2025-09-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
    ]
