# Generated by Django 5.2.1 on 2025-07-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitylog',
            old_name='customer',
            new_name='user',
        ),
    ]
