# Generated by Django 5.2.1 on 2025-08-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_supportmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
