# Generated by Django 5.2.1 on 2025-08-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_supportchat_is_read_alter_supportchat_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='supportchat',
            options={'ordering': ['created_at'], 'verbose_name': 'Support Chat Message', 'verbose_name_plural': 'Support Chat Messages'},
        ),
    ]
