# Generated by Django 5.2.1 on 2025-09-16 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transaction_bill_type_transaction_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE_ID', 'Face ID')], max_length=20)),
                ('fingerprint_template', models.BinaryField(blank=True, null=True)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_data', to='bank.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='BiometricAuth',
        ),
    ]
