# Generated by Django 5.2.1 on 2025-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_supportmessage_file_alter_supportmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeposition',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
