# Generated by Django 5.2.1 on 2025-09-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_biometricdata_delete_biometricauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiometricData',
        ),
    ]
