# Generated by Django 5.2.1 on 2025-08-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_tradeposition_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(default='sdyifjhgksudhjyxhlfhishdufykxjhlgijokasöjldfhibukshadyjlkxyfasoidlkyfhxoaidskl', max_length=225),
        ),
    ]
