# Generated by Django 5.2.1 on 2025-08-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_supportticket_options_supportticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='bank.account'),
        ),
    ]
