# Generated by Django 5.2.1 on 2025-07-31 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('STARTER', 'Starter'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration_days', models.PositiveIntegerField()),
                ('roi_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('features', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CHECKING', 'Checking Account'), ('FIXED', 'Fixed Deposit'), ('INVESTMENT', 'Investment Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('TRANSACTION', 'Transaction'), ('BIOMETRIC_UPDATE', 'Biometric Update'), ('TRADE_EXECUTED', 'Trade Executed'), ('INVESTMENT_CREATED', 'Investment Created')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TRANSFER', 'Bank Transfer'), ('BTC', 'BTC'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BILL_PAYMENT', 'Bill Payment'), ('INVESTMENT', 'Investment'), ('TRADE', 'Trade')], max_length=20),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_return', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.investmentpackage')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.investment'),
        ),
        migrations.CreateModel(
            name='TradePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy (Long)'), ('SELL', 'Sell (Short)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('leverage', models.PositiveIntegerField(default=1)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('take_profit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='trade_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.tradeposition'),
        ),
    ]
