# Generated by Django 5.2.1 on 2025-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_investmentpackage_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='BTC', max_length=3),
        ),
    ]
