# Generated by Django 5.2.1 on 2025-08-15 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_transaction_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeposition',
            name='amount',
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='scaled_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='tradeposition',
            name='leverage',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
