# Generated by Django 5.2.1 on 2025-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_tradeposition_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeposition',
            name='scaled_price',
        ),
        migrations.AddField(
            model_name='account',
            name='block_account',
            field=models.BooleanField(default=False),
        ),
    ]
