# Generated by Django 5.2.1 on 2025-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_tradeposition_scaled_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeposition',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradeposition',
            name='leverage',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
